spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/postgres
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        dll-auto: update
        show-sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false